Integration Specs
SaneMyburg/blog-app pull request #9
Opened 2023-06-26 22:50 UTC by SaneMyburg

# Blog app - integration specs for views and fix n+1 problems
### In this PR: 

1. I solved the N+1 problem when fetching all posts and their comments for a user.
2. I used  Capybara to write Integration specs as follows:
- For user index page:
  - I can see the username of all other users.
  - I can see the profile picture for each user.
  - I can see the number of posts each user has written.
  - When I click on a user, I am redirected to that user's show page.

- For user show page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see the user's bio.
  - I can see the user's first 3 posts.
  - I can see a button that lets me view all of a user's posts.
  - When I click a user's post, it redirects me to that post's show page.
  - When I click to see all posts, it redirects me to the user's post's index page.

- For user post index page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see a post's title.
  - I can see some of the post's body.
  - I can see the first comments on a post.
  - I can see how many comments a post has.
  - I can see how many likes a post has.
  - I can see a section for pagination if there are more posts than fit on the view.
  - When I click on a post, it redirects me to that post's show page.

- For post show page:
  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each comment.
  - I can see the comment each commentor left.

2023-06-27 13:36 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @SaneMyburg, @preciousbetine and @Tracy-miranja,

Good job so far!
✔️ Well-written and passing tests
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-27 13:36 UTC, TedLivist commented on spec/integration/user_index_spec.rb
> +  end
- [ ] **[OPTIONAL]** It is often best to separate these tests into separate blocks to provide a more organized test and explanation. You merged three scenarios into one, but I would advise you split them into three.

2023-06-27 13:36 UTC, TedLivist commented on spec/integration/user_show_spec.rb
> +  end
- [ ] You are missing the test for redirecting to the post's show page when a user clicks on a post. Kindly implement that.

2023-06-27 13:36 UTC, TedLivist commented on spec/integration/post_index_spec.rb
> +    end
- [ ] I don't think the description for this test fits the actual test. It should check for post title, not all posts.

2023-06-27 13:36 UTC, TedLivist commented on spec/integration/post_index_spec.rb
> +  end
- [ ] You are missing the test for redirecting to post show page when a user clicks on a post. Kindly add that.

2023-06-27 13:36 UTC, TedLivist commented on spec/integration/post_show_spec.rb
> +    end
- [ ] You are missing tests for the following scenarios:

  - Tests that asserts you can see who wrote the post.

2023-06-28 02:04 UTC, Davidosky007 requested changes
Hi @SaneMyburg 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* N+1 issue solved 👍 
* Integration test written with capybara gem 👍 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 02:04 UTC, Davidosky007 commented on spec/integration/post_show_spec.rb
> +    end
* This test still missing , kindly add it

2023-06-28 11:12 UTC, Reem-lab approved these changes
# Hi Team,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights
- [ ] Great job on the funtionality for the tests💯
- [ ] Followed Gitflow 🔥
- [ ] No Linters error ✅
- [ ] All tests are passed 💯💯
- [ ] Kudos wokring on solving the `n+1` problems⭐


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 16:18 UTC, merged